# These are supported funding model platforms

github: [manucian-official, tuikobtnghe]
patreon: khoi
open_collective: khoi
ko_fi: khoi
tidelift: khoi
community_bridge: khoi
liberapay: khoi
issuehunt: khoi
lfx_crowdfunding: khoi
polar: khoi
buy_me_a_coffee: khoi
thanks_dev: khoi

